2021-01-06 03:24:28,220UTC: ERROR:root:(<type 'exceptions.RuntimeError'>, RuntimeError('What?',), <traceback object at 0x00000000035F6788>)
2021-01-06 03:24:28,221UTC: INFO:root:Hello, world!
2021-01-06 03:25:43,901UTC: INFO:root:What's up?
2021-01-07 01:05:46,673UTC: DEBUG:root:Hello, world!
2021-01-07 01:07:59,378UTC: DEBUG:root:Hello, world!
2021-01-07 01:10:24,746UTC: ERROR:root:Type RuntimeError: What? in c:\Users\Rob\source\repos\Automation\Labs\lab_utils.py at line 104.
2021-01-07 01:10:24,747UTC: DEBUG:root:Hello, world!
2021-01-07 01:11:21,882UTC: DEBUG:root:Hello, world!
2021-01-07 01:15:52,240UTC: ERROR:root:Type RuntimeError: What? in c:\Users\Rob\source\repos\Automation\Labs\lab_utils.py at line 104.
2021-01-07 01:15:52,242UTC: DEBUG:root:Hello, world!
2021-01-22 01:37:01,245UTC: DEBUG:root:ping -c 4 192.168.1.20: Operation timed out.
2021-01-22 01:39:32,093UTC: DEBUG:root:ping -c 4 192.168.1.20: Operation timed out.
2021-01-22 01:46:02,873UTC: DEBUG:root:ping -c 4 192.168.1.20: Operation timed out.
2021-01-22 02:46:40,033UTC: DEBUG:root:ping -c 4 192.168.1.20: Operation timed out.
2021-01-22 02:50:40,314UTC: DEBUG:root:ping -c 4 192.168.1.20: Operation timed out.
2021-01-22 02:51:41,238UTC: DEBUG:root:ping -c 4 192.168.1.20: Operation timed out.
2021-01-22 03:21:23,619UTC: DEBUG:root:ping -c 4 192.168.1.20: Error - b'PING 192.168.1.20 (192.168.1.20) 56(84) bytes of data.\r\n\r\n--- 192.168.1.20 ping statistics ---\r\n4 packets transmitted, 0 received, 100% packet loss, time 2999ms\r\n\r\n'
2021-01-22 03:31:51,697UTC: DEBUG:root:ping -c 4 192.168.1.20: Error - b'PING 192.168.1.20 (192.168.1.20) 56(84) bytes of data.\r\n\r\n--- 192.168.1.20 ping statistics ---\r\n4 packets transmitted, 0 received, 100% packet loss, time 2999ms\r\n\r\n'
2021-01-22 03:51:31,314UTC: DEBUG:root:ping -c 4 192.168.1.20: Error - b'PING 192.168.1.20 (192.168.1.20) 56(84) bytes of data.\r\n\r\n--- 192.168.1.20 ping statistics ---\r\n4 packets transmitted, 0 received, 100% packet loss, time 3000ms\r\n\r\n'
2021-01-22 03:59:27,438UTC: DEBUG:root:ping -c 4 192.168.1.20: Error - b'PING 192.168.1.20 (192.168.1.20) 56(84) bytes of data.\r\n\r\n--- 192.168.1.20 ping statistics ---\r\n4 packets transmitted, 0 received, 100% packet loss, time 3011ms\r\n\r\n'
2021-01-22 04:01:06,428UTC: DEBUG:root:ping -c 4 192.168.1.20: Error - b'PING 192.168.1.20 (192.168.1.20) 56(84) bytes of data.\r\n\r\n--- 192.168.1.20 ping statistics ---\r\n4 packets transmitted, 0 received, 100% packet loss, time 3000ms\r\n\r\n'
2021-01-22 04:01:40,478UTC: DEBUG:root:ping -c 4 192.168.1.20: Operation timed out.
2021-01-22 04:07:21,541UTC: DEBUG:root:1: Error - Code 1, output b'PING 192.168.1.20 (192.168.1.20) 56(84) bytes of data.\n\n--- 192.168.1.20 ping statistics ---\n4 packets transmitted, 0 received, 100% packet loss, time 3005ms\n\n'.
2021-01-22 04:07:24,666UTC: DEBUG:root:ping -c 4 192.168.1.20: Operation timed out.
2021-01-22 04:08:24,552UTC: DEBUG:root:1: Error - Code 1, output b'PING 192.168.1.20 (192.168.1.20) 56(84) bytes of data.\n\n--- 192.168.1.20 ping statistics ---\n4 packets transmitted, 0 received, 100% packet loss, time 3001ms\n\n'.
2021-01-22 04:08:37,663UTC: DEBUG:root:ping -c 4 192.168.1.20: Error - b'PING 192.168.1.20 (192.168.1.20) 56(84) bytes of data.\r\n\r\n--- 192.168.1.20 ping statistics ---\r\n4 packets transmitted, 0 received, 100% packet loss, time 3000ms\r\n\r\n'
2021-01-22 04:10:03,942UTC: DEBUG:root:ping -c 4 192.168.1.20: Error - Code 1, Output b'PING 192.168.1.20 (192.168.1.20) 56(84) bytes of data.\n\n--- 192.168.1.20 ping statistics ---\n4 packets transmitted, 0 received, 100% packet loss, time 3009ms\n\n'.
2021-01-22 04:10:17,059UTC: DEBUG:root:ping -c 4 192.168.1.20: Error - b'PING 192.168.1.20 (192.168.1.20) 56(84) bytes of data.\r\n\r\n--- 192.168.1.20 ping statistics ---\r\n4 packets transmitted, 0 received, 100% packet loss, time 3003ms\r\n\r\n'
2021-01-23 02:47:28,407UTC: DEBUG:root:ls -l: Pass content not found - b'total 40\r\n-rw-rw-r--. 1 gns3user gns3user 1172 Jan 21 23:41 g000_serial.py\r\n-rw-rw-r--. 1 gns3user gns3user 3606 Jan 21 23:41 g001_ping.py\r\n-rw-rw-r--. 1 gns3user gns3user 2105 Jan 21 23:41 g002_telnet.py\r\n-rw-rw-r--. 1 gns3user gns3user 3830 Jan 19 22:55 g003_setupssh.py\r\n-rw-rw-r--. 1 gns3user gns3user  502 Jan 19 22:55 g063_tftp.py\r\n-rw-rw-r--. 1 gns3user gns3user  140 Jan 21 19:04 __init__.py\r\n-rw-rw-r--. 1 gns3user gns3user 3914 Jan 21 23:10 labs.log\r\n-rw-rw-r--. 1 gns3user gns3user 5317 Jan 22 21:47 lab_utils.py\r\ndrwxrwxr-x. 2 gns3user gns3user   69 Jan 22 21:47 __pycache__\r\ndrwxrwxr-x. 2 gns3user gns3user   31 Jan  7 22:50 utests\r\n-rw-rw-r--. 1 gns3user gns3user  357 Jan 22 21:46 xtest.py\r\n'
2021-01-23 02:50:14,547UTC: DEBUG:root:Script /home/gns3user/repos/Automation/labs/lab_utils.py cannot be run independently from this application.
2021-01-23 04:22:04,385UTC: DEBUG:root:ls -l: Pass content not found - total 44
-rw-rw-r--. 1 gns3user gns3user 1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user 3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user 2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user 3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user  502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user  140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 4866 Jan 22 21:50 labs.log
-rw-rw-r--. 1 gns3user gns3user 5498 Jan 22 23:20 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user   69 Jan 22 23:20 __pycache__
drwxrwxr-x. 2 gns3user gns3user   31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user  698 Jan 22 23:22 xtest.py

2021-01-23 04:26:45,969UTC: DEBUG:root:ls -l: Fail content found - total 44
-rw-rw-r--. 1 gns3user gns3user 1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user 3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user 2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user 3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user  502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user  140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 5644 Jan 22 23:22 labs.log
-rw-rw-r--. 1 gns3user gns3user 5531 Jan 22 23:26 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user   69 Jan 22 23:26 __pycache__
drwxrwxr-x. 2 gns3user gns3user   31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user  717 Jan 22 23:26 xtest.py

2021-01-23 04:27:12,696UTC: DEBUG:root:ls -l: Fail content found - total 44
-rw-rw-r--. 1 gns3user gns3user 1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user 3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user 2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user 3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user  502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user  140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 6418 Jan 22 23:26 labs.log
-rw-rw-r--. 1 gns3user gns3user 5531 Jan 22 23:26 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user   69 Jan 22 23:26 __pycache__
drwxrwxr-x. 2 gns3user gns3user   31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user  731 Jan 22 23:27 xtest.py

2021-01-23 04:34:58,445UTC: DEBUG:root:ls -l: Fail content found - total 44
-rw-rw-r--. 1 gns3user gns3user 1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user 3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user 2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user 3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user  502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user  140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 7192 Jan 22 23:27 labs.log
-rw-rw-r--. 1 gns3user gns3user 5531 Jan 22 23:26 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user   69 Jan 22 23:26 __pycache__
drwxrwxr-x. 2 gns3user gns3user   31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user  436 Jan 22 23:34 xtest.py

2021-01-23 04:41:17,143UTC: DEBUG:root:ls -l: Fail content found: total 44
-rw-rw-r--. 1 gns3user gns3user 1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user 3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user 2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user 3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user  502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user  140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 7966 Jan 22 23:34 labs.log
-rw-rw-r--. 1 gns3user gns3user 5528 Jan 22 23:41 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user   69 Jan 22 23:41 __pycache__
drwxrwxr-x. 2 gns3user gns3user   31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user  508 Jan 22 23:41 xtest.py

2021-01-23 04:41:17,371UTC: DEBUG:root:ping -c 4 198.168.1.300: Error: ping: 198.168.1.300: Name or service not known

2021-01-23 04:42:26,987UTC: DEBUG:root:ls -l: Fail content found: total 48
-rw-rw-r--. 1 gns3user gns3user 1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user 3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user 2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user 3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user  502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user  140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 8859 Jan 22 23:41 labs.log
-rw-rw-r--. 1 gns3user gns3user 5528 Jan 22 23:41 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user   69 Jan 22 23:41 __pycache__
drwxrwxr-x. 2 gns3user gns3user   31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user  508 Jan 22 23:42 xtest.py

2021-01-23 04:42:32,099UTC: DEBUG:root:ping -c 4 198.168.1.212: Operation timed out.
2021-01-23 04:51:38,648UTC: DEBUG:root:ls -l: Fail content found: total 48
-rw-rw-r--. 1 gns3user gns3user 1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user 3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user 2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user 3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user  502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user  140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 9717 Jan 22 23:42 labs.log
-rw-rw-r--. 1 gns3user gns3user 5528 Jan 22 23:41 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user   69 Jan 22 23:41 __pycache__
drwxrwxr-x. 2 gns3user gns3user   31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user  508 Jan 22 23:42 xtest.py

2021-01-23 04:51:43,762UTC: DEBUG:root:ping -c 4 198.168.1.212: Operation timed out.
2021-01-23 04:54:47,619UTC: DEBUG:root:ls -l: Fail content found: total 48
-rw-rw-r--. 1 gns3user gns3user  1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user  3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user  2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user  3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user   502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user   140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 10575 Jan 22 23:51 labs.log
-rw-rw-r--. 1 gns3user gns3user  5528 Jan 22 23:41 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user    69 Jan 22 23:41 __pycache__
drwxrwxr-x. 2 gns3user gns3user    31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user   505 Jan 22 23:54 xtest.py

2021-01-23 04:54:52,738UTC: DEBUG:root:ping -c 4 198.168.1.212: Operation timed out.
2021-01-23 04:55:41,550UTC: DEBUG:root:ls -l: Fail content found: total 48
-rw-rw-r--. 1 gns3user gns3user  1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user  3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user  2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user  3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user   502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user   140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 11444 Jan 22 23:54 labs.log
-rw-rw-r--. 1 gns3user gns3user  5536 Jan 22 23:55 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user    69 Jan 22 23:55 __pycache__
drwxrwxr-x. 2 gns3user gns3user    31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user   505 Jan 22 23:54 xtest.py
2021-01-23 04:55:46,668UTC: DEBUG:root:ping -c 4 198.168.1.212: Operation timed out.
2021-01-23 04:59:15,966UTC: DEBUG:root:ls -l: Fail content found: total 52
-rw-rw-r--. 1 gns3user gns3user  1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user  3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user  2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user  3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user   502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user   140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 12311 Jan 22 23:55 labs.log
-rw-rw-r--. 1 gns3user gns3user  5536 Jan 22 23:55 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user    69 Jan 22 23:55 __pycache__
drwxrwxr-x. 2 gns3user gns3user    31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user   506 Jan 22 23:59 xtest.py
2021-01-23 04:59:29,075UTC: DEBUG:root:ping -c 4 198.168.1.212: Error: PING 198.168.1.212 (198.168.1.212) 56(84) bytes of data.

--- 198.168.1.212 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 2999ms
2021-01-23 05:02:27,516UTC: DEBUG:root:ls -l: Fail content found: total 52
-rw-rw-r--. 1 gns3user gns3user  1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user  3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user  2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user  3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user   502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user   140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 13328 Jan 22 23:59 labs.log
-rw-rw-r--. 1 gns3user gns3user  5536 Jan 22 23:55 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user    69 Jan 22 23:55 __pycache__
drwxrwxr-x. 2 gns3user gns3user    31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user   488 Jan 23 00:02 xtest.py
2021-01-23 05:02:30,655UTC: DEBUG:root:ping -c 4 8.8.8.8: Pass content not found: PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=38.6 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=117 time=17.5 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=117 time=16.0 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=117 time=15.7 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3007ms
rtt min/avg/max/mdev = 15.702/21.977/38.649/9.649 ms
2021-01-23 05:02:46,286UTC: DEBUG:root:ls -l: Fail content found: total 52
-rw-rw-r--. 1 gns3user gns3user  1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user  3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user  2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user  3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user   502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user   140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 14614 Jan 23 00:02 labs.log
-rw-rw-r--. 1 gns3user gns3user  5536 Jan 22 23:55 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user    69 Jan 22 23:55 __pycache__
drwxrwxr-x. 2 gns3user gns3user    31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user   500 Jan 23 00:02 xtest.py
2021-01-23 05:02:49,446UTC: DEBUG:root:ping -c 4 8.8.8.8: Pass content not found: PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=16.4 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=117 time=17.5 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=117 time=20.5 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=117 time=19.3 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 16.463/18.456/20.523/1.576 ms
2021-01-23 05:04:52,027UTC: DEBUG:root:ls -l: Fail content found: total 52
-rw-rw-r--. 1 gns3user gns3user  1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user  3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user  2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user  3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user   502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user   140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 15900 Jan 23 00:02 labs.log
-rw-rw-r--. 1 gns3user gns3user  5532 Jan 23 00:04 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user    69 Jan 23 00:04 __pycache__
drwxrwxr-x. 2 gns3user gns3user    31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user   500 Jan 23 00:02 xtest.py
2021-01-23 05:04:55,158UTC: DEBUG:root:ping -c 4 8.8.8.8: Pass content not found: PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=17.9 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=117 time=16.9 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=117 time=19.5 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=117 time=16.5 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 16.522/17.756/19.554/1.173 ms
2021-01-23 05:08:18,461UTC: DEBUG:root:ls -l: Fail content found: total 56
-rw-rw-r--. 1 gns3user gns3user  1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user  3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user  2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user  3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user   502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user   140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 17186 Jan 23 00:04 labs.log
-rw-rw-r--. 1 gns3user gns3user  5565 Jan 23 00:08 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user    69 Jan 23 00:08 __pycache__
drwxrwxr-x. 2 gns3user gns3user    31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user   500 Jan 23 00:02 xtest.py
2021-01-23 05:08:21,613UTC: DEBUG:root:ping -c 4 8.8.8.8: Pass content not found: PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=20.8 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=117 time=18.9 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=117 time=19.6 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=117 time=17.8 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3006ms
rtt min/avg/max/mdev = 17.851/19.335/20.815/1.090 ms
2021-01-23 05:08:58,936UTC: DEBUG:root:ping -c 4 8.8.8.8: Pass content not found: PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=27.6 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=117 time=24.5 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=117 time=25.0 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=117 time=28.5 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 24.578/26.452/28.541/1.669 ms
2021-01-23 05:10:11,699UTC: DEBUG:root:Script /home/gns3user/repos/Automation/labs/lab_utils.py cannot be run independently from this application.
2021-01-23 05:10:24,169UTC: DEBUG:root:ping -c 4 8.8.8.8: Pass content not found: PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=20.7 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=117 time=16.5 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=117 time=18.0 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=117 time=19.3 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 16.528/18.688/20.793/1.574 ms
2021-01-23 05:14:57,027UTC: DEBUG:root:ping -c 4 8.8.8.8: Pass content not found: PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=16.4 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=117 time=17.5 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=117 time=18.9 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=117 time=18.6 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 16.410/17.896/18.930/1.006 ms
2021-01-23 05:29:25,699UTC: DEBUG:root:ls -l: Fail content found: total 56
-rw-rw-r--. 1 gns3user gns3user  1172 Jan 21 23:41 g000_serial.py
-rw-rw-r--. 1 gns3user gns3user  3606 Jan 21 23:41 g001_ping.py
-rw-rw-r--. 1 gns3user gns3user  2105 Jan 21 23:41 g002_telnet.py
-rw-rw-r--. 1 gns3user gns3user  3830 Jan 19 22:55 g003_setupssh.py
-rw-rw-r--. 1 gns3user gns3user   502 Jan 19 22:55 g063_tftp.py
-rw-rw-r--. 1 gns3user gns3user   140 Jan 21 19:04 __init__.py
-rw-rw-r--. 1 gns3user gns3user 20131 Jan 23 00:14 labs.log
-rw-rw-r--. 1 gns3user gns3user  5579 Jan 23 00:29 lab_utils.py
drwxrwxr-x. 2 gns3user gns3user    69 Jan 23 00:29 __pycache__
drwxrwxr-x. 2 gns3user gns3user    31 Jan  7 22:50 utests
-rw-rw-r--. 1 gns3user gns3user   523 Jan 23 00:29 xtest.py
2021-01-23 05:47:21,773UTC: DEBUG:root:ping -c 4 8.8.8.8: Error: PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
From 192.168.1.1 icmp_seq=1 Destination Host Unreachable
From 192.168.1.1 icmp_seq=2 Destination Host Unreachable
From 192.168.1.1 icmp_seq=3 Destination Host Unreachable
From 192.168.1.1 icmp_seq=4 Destination Host Unreachable

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 0 received, +4 errors, 100% packet loss, time 3035ms
pipe 4
2021-01-29 03:05:06,540UTC: DEBUG:root:ping -c 4 8.8.8.8: Error: PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
From 192.168.1.1 icmp_seq=1 Destination Host Unreachable
From 192.168.1.1 icmp_seq=2 Destination Host Unreachable
From 192.168.1.1 icmp_seq=3 Destination Host Unreachable
From 192.168.1.1 icmp_seq=4 Destination Host Unreachable

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 0 received, +4 errors, 100% packet loss, time 3000ms
pipe 4
2021-01-29 03:09:48,479UTC: DEBUG:root:pgrep gns3server: Error: 
2021-01-29 03:51:05,373UTC: DEBUG:root:pgrep gns3server: Error: 
2021-01-29 03:54:16,668UTC: DEBUG:root:pgrep gns3server: Error: 
2021-01-29 03:54:44,542UTC: DEBUG:root:pgrep gns3server: Error: 
